### ISSUE TITLE
not using preventDefault().

### ISSUE THREAD

**Issue by RyszardRzepa** [scalable-react/scalable-react-boilerplate#78]
Hey Ryan!

So far it is the best react boilerplate i found! 
Great job!!

Thanks to you I discovered groomet UI framework. It's a amazing tool.

I ma just wondering why you are not using preventDefault() to prevent refreshing the pages during the navigation? 

Ryszard

**Comment by RyanCCollins** [comment]
Hey @RyszardRzepa, I would recommend using the [Anchor component'](https://grommet.github.io/docs/anchor)s path vs. href.  The grommet team added this a few months ago and I have yet to have a chance to update the source code for the example site.


Thank you for your kind words and I am glad you found Grommet!! I recently joined their team.  They are all-stars in my mind.

If you get a chance to, I'd love a PR that fixes the nav links.  Otherwise, I can do it shortly.

All the best!
